task1
maxNia/ITA-back-express pull request #2
Opened 2021-06-23 15:57 UTC by maxNia

<img width="776" alt="Снимок экрана 2021-06-23 в 18 47 57" src="https://user-images.githubusercontent.com/80146409/123131130-133d6a00-d456-11eb-9e8e-5802452ce1c7.png">
try to upload some fields
<img width="411" alt="Снимок экрана 2021-06-23 в 18 48 08" src="https://user-images.githubusercontent.com/80146409/123131191-20f2ef80-d456-11eb-98ce-59fcd4960334.png">
after update the second field from 'nikita' to 'NiKITA'

2021-06-24 09:24 UTC, CatDidenko requested changes

2021-06-24 09:24 UTC, CatDidenko commented on src/list/list.model.ts
> +    type: 'VARCHAR(36)',
should be uuiv4 type and autogenerated

2021-06-24 09:24 UTC, CatDidenko commented on src/contact/contact.services.ts
> +    await Contact.update(body, {
I suggested not to use models for querying in this task, but write SQL queries with the help of sequelize.query

2021-06-24 09:24 UTC, CatDidenko commented on src/contact/contact.services.ts
> +    await Contact.create({uuid, name, email});
I suggested not to use models for querying in this task, but write SQL queries with the help of sequelize.query

2021-06-24 18:17 UTC, maxNia commented on src/list/list.model.ts
> +    type: 'VARCHAR(36)',
updated

2021-06-24 20:46 UTC, maxNia commented on src/contact/contact.services.ts
> +    await Contact.create({uuid, name, email});
updated

2021-06-24 20:46 UTC, maxNia commented on src/contact/contact.services.ts
> +    await Contact.update(body, {
updated

2021-06-25 21:09 UTC, CatDidenko approved these changes

2021-06-28 05:05 UTC, merged